version: '3.4'

services:
  # psyassistplatform.authservice.webapi:
  #   image: psyassistplatform.authservice.webapi
  #   build:
  #     context: .
  #     dockerfile: PsyAssistPlatform.AuthService.WebApi/Dockerfile

  psyassistplatform.authservice.db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
