services:
  # authservice:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - ./PsyAssistPlatform.AuthService.WebApi/keys/certificate.pfx:/app/certificate.pfx
  #   depends_on:
  #     - db

  db:
    build:
      context: .
      dockerfile: ./Dockerfile_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/home/alexey/postgresql_data
    user: "1000:1000"

volumes:
  pgdata:
    driver: local