version: '3.8'

services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:80"
      - "7443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

